name: Publish NuGet Package

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Set version suffix
        id: version
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "suffix=-dev" >> $GITHUB_OUTPUT
          else
            echo "suffix=" >> $GITHUB_OUTPUT
          fi

      - name: Pack
        run: |
          dotnet pack Fuxion.Ali.Contracts/Fuxion.Ali.Contracts.csproj \
            --configuration Release \
            --output ./nupkg \
            /p:VersionSuffix=${{ steps.version.outputs.suffix }}

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Clean up
        run: rm -rf ./nupkg